backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: 'static/photos'
public_folder: '/photos'

collections:
  - name: 'photos'
    label: 'Photos'
    label_singular: 'Photo'
    identifier_field: image
    folder: 'src/content/photos'
    create: true
    # Create custom widget for slug: https://github.com/netlify/netlify-cms/issues/445#issuecomment-824499171
    slug: '{{year}}-{{month}}-{{day}}'
    fields:
      - { label: 'Image', name: 'image', widget: 'image', allow_multiple: false, choose_url: false }
      - {
          label: 'Langue',
          name: 'lang',
          widget: 'select',
          default: 'fr',
          options: [{ label: 'Français', value: 'fr' }, { label: 'English', value: 'en' }]
        }
      - { label: 'Alt', name: 'alt', widget: 'text' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Syndicate', name: 'syndicate', widget: 'boolean' }
