backend:
  name: git-gateway
  branch: main

media_folder: 'static/images'
public_folder: '/images'
publish_mode: editorial_workflow

collections:
  - name: 'article'
    label: 'Article'
    folder: 'src/content/articles'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'layout'
    label: 'Layout'
    files:
      - label: Site layout
        name: siteLayout
        file: src/content/layout.json
        fields:
          - { label: 'Page title', name: 'pageTitle', widget: 'string' }
          - { label: 'Footer description', name: 'footerDescription', widget: 'string' }
          - name: 'footerLinks'
            label: 'Footer links'
            widget: list
            fields:
              - { label: 'Href', name: 'href', widget: 'string' }
              - { label: 'Label', name: 'label', widget: 'string' }
