backend:
  name: git-gateway
  branch: main

media_folder: 'static/images'
public_folder: '/images'
publish_mode: editorial_workflow

collections:
  - name: 'article'
    label: 'Articles'
    folder: 'src/articles'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
