backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: 'static/photos'
public_folder: '/photos'

collections:
  - name: 'photos' # Used in routes, e.g., /admin/collections/blog
    label: 'Photos' # Used in the UI
    folder: 'src/content/photos' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {
          label: 'Langue',
          name: 'lang',
          widget: 'select',
          default: 'fr',
          options: [{ label: 'Français', value: 'fr' }, { label: 'English', value: 'en' }]
        }
      - { label: 'Alt', name: 'alt', widget: 'text' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Syndicate', name: 'syndicate', widget: 'boolean' }
